version: "3.9"

services:
  iris:
    build: .
    container_name: iris_app
    env_file:
      - .env.stage.iris
    ports:
      - "3001:3001"

  primrose:
    build: .
    container_name: primrose_app
    env_file:
      - .env.stage.primrose
    ports:
      - "3002:3001"
